import { Router } from "express";
import authRoutes from "./authRoutes";
import projectRoutes from "./projectRoutes";
import logframeRoutes from "./logframeRoutes";
import indicatorRoutes from "./indicatorRoutes";
import submissionRoutes from "./submissionRoutes";
import importRoutes from "./importRoutes";
import exportRoutes from "./exportRoutes";
import templateRoutes from "./templateRoutes";
import healthRoutes from "./healthRoutes";
import notificationRoutes from "./notificationRoutes";
import usersRoutes from "./usersRoutes";
import suppliersRoutes from "./inventoryRoutes";
import customerRoutes from "./customerRoutes";
import productionRoutes from "./productionRoutes";
import salesInvoiceRoutes from "./salesInvoiceRoutes";
import salesOrderRoutes from "./salesOrderRoutes";
import expenseRoutes from "./expenseRoutes";
import operationsRoutes from "./operationsRoutes";
import organizationBankAccountRoutes from "./organizationBankAccountRoutes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/", projectRoutes);
router.use("/", logframeRoutes);
router.use("/", indicatorRoutes);
router.use("/", submissionRoutes);
router.use("/", importRoutes);
router.use("/", exportRoutes);
router.use("/", templateRoutes);
router.use("/", healthRoutes);
router.use("/", notificationRoutes);
router.use("/users", usersRoutes);
router.use("/inventory", suppliersRoutes);
router.use("/customers", customerRoutes);
router.use("/production", productionRoutes);
router.use("/sales-invoices", salesInvoiceRoutes);
router.use("/sales-orders", salesOrderRoutes);
router.use("/expenses", expenseRoutes);
router.use("/operations", operationsRoutes);
router.use("/organization/bank-accounts", organizationBankAccountRoutes);

export default router;
