[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "garment_factory"
version = "0.0.1"
description = "Garment Factory Frappe app scaffold"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["garment_factory*", "doctype*"]
