version: '3.9'
services:
  mysql:
    image: mysql:8.4
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: merlin_lite
      MYSQL_ROOT_PASSWORD: postgres
      MYSQL_USER: merlin
      MYSQL_PASSWORD: postgres
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata:
